name: fun_components
version: 0.6.0
author: James Hurford <terrasea@gmail.com>
description: Polymer components made for fun
homepage: https://github.com/terrasea/fun_components
dependencies:
  credit_cat: '>=0.2.4 <0.3.0'
  gravatar: '>=1.2.3 <1.3.0'
  html5lib: any
  intl: any
  markdown: '>=0.7.0 <0.8.0'
  polymer: "^1.0.0-rc.1"
  web_components: "^0.12.0+3"
  reflectable: any
  polymer_interop: "^1.0.0-rc.1"
  polymer_elements: "^1.0.0-rc.1"
  roman_numerals: '>=1.0.2 <1.1.0'
  turkish_numbers: '>=0.1.0 <0.2.0'
  xml2json: any
dev_dependencies:
  test: any
#dependency_overrides:
#  reflectable: "0.2.1"
transformers:
- web_components:
    entry_points:
    - test/index.html
- reflectable:
    entry_points:
    - test/test.dart
- test/pub_serve:
    $include: test/**test.dart
- $dart2js:
    minify: true

environment:
  sdk: ">=1.2.0 <2.0.0"